from data_generator import *
from metadata import get_metadata

wsi_files_with_metadata,filtered_metadata = get_metadata()
# TESTING DATA GENERATOR
dataset = WSI_MONAI_Dataset(
    repo_id=wsi_repo_id,
    file_list=wsi_files_with_metadata[:3],
    metadata=filtered_metadata,
    num_patches=4,
    patch_size=224,
    patch_level=0
)

patches, label = dataset[0]
icd10_label = dataset.get_icd10_from_idx(label.item())

fig, axes = plt.subplots(1, 4, figsize=(16, 4))
fig.suptitle(f'MODEL INPUT - THE PATCHES GENERATED BY DATA GENERATOR SHIFTED TO [0,1] RANGE OF MATPLOTLIB {icd10_label}', fontsize=14)

for i in range(4):
    raw_tensor = patches[i]
    display_tensor = (raw_tensor - raw_tensor.min()) / (raw_tensor.max() - raw_tensor.min())
    
    axes[i].imshow(display_tensor.permute(1, 2, 0).numpy())
    axes[i].set_title(f'Raw Tensor {i}\nRange: [{display_tensor.min():.2f}, {display_tensor.max():.2f}]')
    axes[i].axis('off')

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 4, figsize=(16, 4))
fig.suptitle(f'RAW MODEL INPUT - What EXAONEPath Actually Sees - ICD-10: {icd10_label}', fontsize=14)

for i in range(4):        
    axes[i].imshow(patches[i].permute(1, 2, 0).numpy())
    axes[i].set_title(f'Raw Tensor {i}\nRange: [{raw_tensor.min():.2f}, {raw_tensor.max():.2f}]')
    axes[i].axis('off')

plt.tight_layout()
plt.show()