name: exaonepath
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.3
  - pytorch==2.2.0
  - pytorch-cuda=11.8
  - torchvision==0.17.0
  - cudatoolkit=11.8
  - pandas
  - pillow==10.0.1
  - pip
  - pip:
    - huggingface-hub==0.23.4
    - torchstain>=1.3.0
    - transformers==4.43.3